spring.application.name=transacciones
server.servlet.context-path=/transacciones
server.port=8080

#spring.datasource.url=jdbc:h2:~/testdb
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

#ver consola admoon:  http://localhost:8080/transacciones/h2-console
#cambiar en JDBC URL:	jdbc:h2:mem:testdb
